### PR TITLE
Deep cleaning of tayara.tn price feature

### PR DESCRIPTION
**Pull request by neirezcher**
I conducted a manual inspection of the dataset to address rows that did not pertain to apartment-type announcements and identified duplicates. Additionally, I worked on aligning the price column values by adjusting inconsistencies. Despite these efforts, rows with incomplete or messy data, such as missing price values, had to be removed, ultimately leaving us with only 579 rows.
Before proceeding further, I recommend conducting a more thorough inspection of the data to ensure its quality and consistency.

### CODE REVIEW

**Comment by anasneji2002** [comment]
random questions : the price units are only wrong for tayara.csv file , have you checked other files

**Comment by anasneji2002** [comment]
another question why are we only identifying rows with price 0.0, 1.0, 2.0, 2.5 (why not check for values less than 10 ?)
other than that lgtm

**Comment by neirezcher** [comment]
To address the first question from @anasneji2002 , I inspected only the data from the tayara.csv file, as you had requested assistance with it earlier.
Regarding the second question, the values 0.0, 1.0, 2.0, and 2.5 serve as placeholders for empty price fields. During my inspection, I identified rows with these placeholders. Alternatively, checking for price values less than 10 would yield the same results. Moreover, rows with 2.0 and 2.5 as placeholders are significantly less common compared to those with 0.0 and 1.0.

**Comment by anasneji2002** [comment]
> To address the first question from @anasneji2002 , I inspected only the data from the tayara.csv file, as you had requested assistance with it earlier. Regarding the second question, the values 0.0, 1.0, 2.0, and 2.5 serve as placeholders for empty price fields. During my inspection, I identified rows with these placeholders. Alternatively, checking for price values less than 10 would yield the same results. Moreover, rows with 2.0 and 2.5 as placeholders are significantly less common compared to those with 0.0 and 1.0.

I think we should inspect other files as well , I remember mentioning tayara.csv as an example for files with corrupted data , other files could also have prices not in the unit agreed upon (TND)
Please check for other files anomalies as well

**Review by ahmedrezgui — APPROVED** [review]

**Pull request merged**
